"""Named LED-pattern presets for `/led_control`, on disk on the ground station.

Mirrors the split in `tuning.py`, for the same reason:

1. **`validate_frames()`** - the same frame/pixel/hold_ms shape `/api/command`'s
   `set_lights_pattern` accepts and `ligmax-pi/nodes/io_manager/lights.py`'s
   `_parse_pattern()` parses on the vessel. Factored out here so `/led_control`'s
   "save" path and its "send to boat" path validate against one definition
   instead of two copies that could drift apart.

2. **`EffectStore`** - named snapshots of a pattern, kept in one JSON file, the
   same load-whole/rewrite-whole/write-tmp-then-rename shape as
   `tuning.ProfileStore`. `/led_control` itself holds no state between loads -
   a pattern authored in the browser lives only in that tab until Save writes
   it here - so without this, closing the tab lost every effect that had not
   just been sent to the boat. This is the second thing in `ligmax-server`
   that writes to disk; `tuning.ProfileStore` is the first, and both exist for
   the same reason: some state here is expensive to recreate and cheap to
   store, which is the wrong trade for RAM-only.

The store reads **two** files, and the difference between them is the whole
reason the second exists:

* `light-effects.json` - what this operator saved. Gitignored, machine-local,
  written here.
* `light-effects-examples.json` - the bundled examples, generated by
  `tools/gen_light_effects.py`. Committed, identical in every checkout, and
  **never written**: `_flush()` only ever serialises the saved half, so an
  example cannot be edited into someone's working tree by using the GUI.

They are listed together and load into the editor identically - an example is
a starting point, not a separate kind of thing - but each carries
`"example": true` so `/led_control` can group them and refuse to offer Delete.
Saving over an example's name is refused rather than shadowing it, so a name
in the list means exactly one pattern.
"""

from __future__ import annotations

import json
import os
import re
import threading
import time
from pathlib import Path
from typing import Any

# Mirrors ligmax-pi/nodes/io_manager/lights.py's NUM_LEDS/MAX_PATTERN_FRAMES/
# MIN_HOLD_S/MAX_HOLD_S defaults, exactly like server.py's own copy of these
# used to (now delegated here) - kept in step so a pattern that validates on
# this box is one the vessel will actually accept.
#
# 100, not 101, since 2026-08-10: one LED in the strip's 22-long forward-right
# segment failed and was wired out rather than replaced, so that segment is 21
# and the strip is 100 long - see lights_esp.ino's header and lights.py's own
# NUM_LEDS default.
NUM_LEDS = 100
MAX_FRAMES = 60
MIN_HOLD_MS = 20
MAX_HOLD_MS = 60_000
_HEX_COLOUR_RE = re.compile(r"^#?[0-9A-Fa-f]{6}$")

MAX_EFFECTS = 40
MAX_EFFECT_NAME = 40

# The bundled examples, beside this module because they are source: they ship
# with the repo, the same in every checkout, and `tools/gen_light_effects.py`
# is the only thing that writes them. MAX_EFFECTS counts saved effects only,
# so shipping examples never costs the operator a slot.
EXAMPLES_PATH = Path(__file__).resolve().with_name("light-effects-examples.json")


def validate_frames(frames: Any) -> tuple[list[dict[str, Any]] | None, str | None]:
    """`frames` off the wire -> cleaned `[{"pixels": ..., "hold_ms": float}, ...]`,
    or `(None, why)`.
    """
    if not isinstance(frames, list) or not frames:
        return None, "'frames' must be a non-empty list"
    if len(frames) > MAX_FRAMES:
        return None, f"a pattern may have at most {MAX_FRAMES} frames"
    cleaned: list[dict[str, Any]] = []
    for i, entry in enumerate(frames):
        if not isinstance(entry, dict):
            return None, f"frame {i} is not an object"
        try:
            hold_ms = float(entry.get("hold_ms"))
        except (TypeError, ValueError):
            return None, f"frame {i} has a bad hold_ms"
        if not (MIN_HOLD_MS <= hold_ms <= MAX_HOLD_MS):
            return None, (
                f"frame {i} hold_ms must be between {MIN_HOLD_MS} and {MAX_HOLD_MS}"
            )
        pixels = entry.get("pixels")
        if isinstance(pixels, str):
            swatch = [pixels]
        elif isinstance(pixels, list):
            if len(pixels) != NUM_LEDS:
                return None, f"frame {i} has {len(pixels)} pixels, want {NUM_LEDS}"
            swatch = pixels
        else:
            return None, f"frame {i} pixels must be a hex string or a list"
        for value in swatch:
            if not _HEX_COLOUR_RE.match(str(value)):
                return None, f"frame {i} has a bad colour {value!r}"
        cleaned.append({"pixels": pixels, "hold_ms": hold_ms})
    return cleaned, None


class EffectStore:
    """Named LED patterns: the operator's own, plus the bundled examples."""

    def __init__(
        self, path: str | Path, examples_path: str | Path | None = EXAMPLES_PATH
    ) -> None:
        self.path = Path(path)
        self.examples_path = Path(examples_path) if examples_path else None
        self._lock = threading.Lock()
        self._effects: dict[str, dict[str, Any]] = {}
        self._examples: dict[str, dict[str, Any]] = {}
        self.last_error: str | None = None
        self.examples_error: str | None = None
        self._load_examples()
        self._load()

    def _read(self, path: Path) -> tuple[dict[str, Any] | None, str | None]:
        """`path` -> its `effects` object, or `(None, why)`. Shared by both
        loads so a saved file and the bundled one are read by one parser."""
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            return None, f"could not read {path}: {exc}"
        effects = raw.get("effects") if isinstance(raw, dict) else None
        if not isinstance(effects, dict):
            return None, f"{path} has no 'effects' object"
        return effects, None

    def _load(self) -> None:
        if not self.path.exists():
            return
        effects, why = self._read(self.path)
        if why is not None:
            # Keep going with no saved effects rather than refusing to start:
            # this file's job is remembering patterns, not gating the server.
            self.last_error = why
            return
        for name, entry in effects.items():
            if not isinstance(entry, dict):
                continue
            frames, why = validate_frames(entry.get("frames"))
            if why is not None:
                continue  # a hand-edited or stale file; skip rather than refuse the rest
            key = str(name)[:MAX_EFFECT_NAME]
            if key in self._examples:
                # An older file from before the examples existed, or a
                # hand-edit. The example wins: it is the one the rest of the
                # team sees under that name, and save() refuses the collision
                # from here on.
                continue
            self._effects[key] = {
                "frames": frames,
                "saved_at": entry.get("saved_at"),
                "saved_by": str(entry.get("saved_by") or "")[:64],
            }

    def _load_examples(self) -> None:
        """The committed examples. A missing or broken file costs the examples
        and nothing else - saving, loading and sending all still work."""
        if self.examples_path is None or not self.examples_path.exists():
            return
        effects, why = self._read(self.examples_path)
        if why is not None:
            self.examples_error = why
            return
        for name, entry in effects.items():
            if not isinstance(entry, dict):
                continue
            frames, why = validate_frames(entry.get("frames"))
            if why is not None:
                self.examples_error = f"example '{name}' is not a valid pattern: {why}"
                continue
            self._examples[str(name)[:MAX_EFFECT_NAME]] = {
                "frames": frames,
                "description": str(entry.get("description") or "")[:200],
            }

    def _flush(self) -> None:
        # `self._effects` only - the examples are source and are never written
        # back, so nothing the GUI does can dirty the committed file.
        payload = {"version": 1, "effects": self._effects}
        temporary = self.path.with_suffix(self.path.suffix + ".tmp")
        temporary.parent.mkdir(parents=True, exist_ok=True)
        temporary.write_text(
            json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8"
        )
        os.replace(temporary, self.path)

    @staticmethod
    def _describe(
        name: str, entry: dict[str, Any], example: bool, with_frames: bool
    ) -> dict[str, Any]:
        described = {
            "name": name,
            "example": example,
            "description": entry.get("description", ""),
            "saved_at": entry.get("saved_at"),
            "saved_by": entry.get("saved_by"),
            "count": len(entry["frames"]),
        }
        if with_frames:
            described["frames"] = entry["frames"]
        return described

    def list(self, with_frames: bool = False) -> list[dict[str, Any]]:
        """Examples first, then the operator's own, each side sorted by name.

        One list, because loading either does the same thing; `example` is
        what tells them apart in the GUI.

        Frames are left out by default, and that default matters: fifteen
        bundled examples are a few hundred kB of hex, `/led_control` re-lists
        every 15 s to notice another admin's save, and it needs one effect's
        frames only when Load is pressed. `entry()` is that fetch.
        """
        with self._lock:
            entries = [
                self._describe(name, entry, True, with_frames)
                for name, entry in sorted(self._examples.items())
            ]
            entries += [
                self._describe(name, entry, False, with_frames)
                for name, entry in sorted(self._effects.items())
            ]
            return entries

    def entry(self, name: str) -> dict[str, Any] | None:
        """One effect, frames included - what Load asks for."""
        key = str(name)[:MAX_EFFECT_NAME]
        with self._lock:
            saved = self._effects.get(key)
            if saved is not None:
                return self._describe(key, saved, False, True)
            example = self._examples.get(key)
            if example is not None:
                return self._describe(key, example, True, True)
            return None

    def get(self, name: str) -> list[dict[str, Any]] | None:
        key = str(name)[:MAX_EFFECT_NAME]
        with self._lock:
            entry = self._effects.get(key) or self._examples.get(key)
            return list(entry["frames"]) if entry else None

    def is_example(self, name: str) -> bool:
        with self._lock:
            return str(name or "")[:MAX_EFFECT_NAME] in self._examples

    def save(
        self, name: str, frames: Any, by: str = ""
    ) -> tuple[dict[str, Any] | None, str | None]:
        clean_name = " ".join(str(name or "").split())[:MAX_EFFECT_NAME]
        if not clean_name:
            return None, "an effect needs a name"
        cleaned, why = validate_frames(frames)
        if why is not None:
            return None, why
        with self._lock:
            if clean_name in self._examples:
                return None, (
                    f"'{clean_name}' is a bundled example; save under another name"
                )
            if clean_name not in self._effects and len(self._effects) >= MAX_EFFECTS:
                return None, f"at most {MAX_EFFECTS} saved effects; delete one first"
            self._effects[clean_name] = {
                "frames": cleaned,
                "saved_at": time.time(),
                "saved_by": str(by)[:64],
            }
            try:
                self._flush()
            except OSError as exc:
                del self._effects[clean_name]
                return None, f"could not write {self.path}: {exc}"
            return {"name": clean_name, "count": len(cleaned)}, None

    def delete(self, name: str) -> tuple[bool, str | None]:
        key = str(name or "")[:MAX_EFFECT_NAME]
        with self._lock:
            if key in self._examples:
                return False, (
                    f"'{key}' is a bundled example and cannot be deleted; "
                    "edit tools/gen_light_effects.py to change it"
                )
            if key not in self._effects:
                return False, f"no effect called '{key}'"
            removed = self._effects.pop(key)
            try:
                self._flush()
            except OSError as exc:
                self._effects[key] = removed
                return False, f"could not write {self.path}: {exc}"
            return True, None
